services:
  db:
    build: ./postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: practice
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/pg_hba.conf:/usr/local/etc/postgres/pg_hba.conf
      - ./postgres/postgresql.conf:/usr/local/etc/postgres/postgresql.conf
    command: postgres -c config_file=/usr/local/etc/postgres/postgresql.conf -c hba_file=/usr/local/etc/postgres/pg_hba.conf
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - GENERIC_TIMEZONE=Europe/Moscow
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  pgdata:
