export const errorMessages = {
  resource_exist: "Resource already exist",
  requiered_fields: "Name and email are required",
  server_error: "Server error",
  data_error: "Database error",
  invalid_data: "Invalid id",
  invalid_token: "Invalid or expired refresh token",
  expired_refresh_token: "Expired refresh token",
  refresh_token_not_found: "Refresh token not found",
  refresh_token_required: "Refresh token is required",
  not_found: "Not found",
  user_not_found: "User not found",
  branch_not_exist: "Branch does not exist",
  invalid_email_or_password: "Invalid email or password",
  authentication_required: "Authentication required",
  admin_access_required: "Admin access required",
  user_already_exists: "User with this email already exists",
  unauthorized: "Unauthorized",
  sse_ticket_required: "sse ticket required",
  invalid_sse_ticket: "invalid sse ticket",
};
